We are now going to deal with Python exceptions
